
#ifndef _CONFIG_H
#define _CONFIG_H

// WiFi configuration parameters
#define WIFI_MAX_RETRIES 5
#define WIFI_CRED_MAX_NUM 10
#define WIFI_CRED_MAX_LINE 128

// MQTT configuration parameters
#define MQTT_BROKER_URI "mqtt://broker.hivemq.com:1883"
#define MQTT_BROKER_PORT 1883
#define MQTT_CLIENT_ID "esp32_client"
#define MQTT_BROKER_USERNAME "SEI"
#define MQTT_BROKER_KEY "SEI"
#define MQTT_BUFFER_SIZE_LEN 256
#define MQTT_TOPIC "esp32/data"
#define MQTT_KEEPALIVE_INTERVAL 20 // seconds

// SPIFFS configuration parameters
#define SPIFFS_BASE_PATH "/spiffs"
#define SPIFFS_MAX_FILES 5
#define SPIFFS_FULL_PATH_SIZE 64
#define WIFI_CRED_FILE "/spiffs/wifi_creds.txt"

#define PATIENT_DATA_DIR "/spiffs/patients"

#define DISPLAY_WIDTH 800
#define DISPLAY_HEIGHT 480
#define DISPLAY_BCKL_PIN GPIO_NUM_2
#define DISPLAY_BCKL_LEDC_TIMER LEDC_TIMER_0
#define DISPLAY_BCKL_LEDC_CHANNEL LEDC_CHANNEL_0
#define DISPLAY_TOUCH_RESET_PIN GPIO_NUM_38
#define DISPLAY_TOUCH_ADDRRESS 0x5D
#define DISPLAY_TOUCH_SCL_PIN GPIO_NUM_20
#define DISPLAY_TOUCH_SDA_PIN GPIO_NUM_19
#define DISPLAY_TOUCH_INT_PIN GPIO_NUM_NC
#define DISPLAY_TOUCH_I2C_PORT 0
#define DISPLAY_TOUCH_I2C_FREQ 100000
#define DISPLAY_DOUBLE_FB true
#define DISPLAY_DOUBLE_FB_TEARING true
#define DISPLAY_USE_BOUNCE_BUFFER false

#define LCD_PIN_B0 GPIO_NUM_8
#define LCD_PIN_B1 GPIO_NUM_3
#define LCD_PIN_B2 GPIO_NUM_46
#define LCD_PIN_B3 GPIO_NUM_9
#define LCD_PIN_B4 GPIO_NUM_1

#define LCD_PIN_G0 GPIO_NUM_5
#define LCD_PIN_G1 GPIO_NUM_6
#define LCD_PIN_G2 GPIO_NUM_7
#define LCD_PIN_G3 GPIO_NUM_15
#define LCD_PIN_G4 GPIO_NUM_16
#define LCD_PIN_G5 GPIO_NUM_4

#define LCD_PIN_R0 GPIO_NUM_45
#define LCD_PIN_R1 GPIO_NUM_48
#define LCD_PIN_R2 GPIO_NUM_47
#define LCD_PIN_R3 GPIO_NUM_21
#define LCD_PIN_R4 GPIO_NUM_14

#define LCD_DATA_WIDTH 16
#define LCD_BITS_PER_PIXEL 16
#define LCD_DMA_BURST_SIZE 64
#define LCD_PCLK_HZ_NORMAL (14 * 1000000)
#define LCD_PCLK_HZ_BOUNCE (18 * 1000000)
#define LCD_HSYNC_PULSE_WIDTH 7
#define LCD_HSYNC_BACK_PORCH 40
#define LCD_HSYNC_FRONT_PORCH 40
#define LCD_VSYNC_PULSE_WIDTH 7
#define LCD_VSYNC_BACK_PORCH 10
#define LCD_VSYNC_FRONT_PORCH 10
#define LCD_HSYNC_GPIO GPIO_NUM_39
#define LCD_VSYNC_GPIO GPIO_NUM_41
#define LCD_DE_GPIO GPIO_NUM_40
#define LCD_PCLK_GPIO GPIO_NUM_42

#define LVGL_TASK_MAX_DELAY_MS 500
#define LVGL_TASK_MIN_DELAY_MS 1
#define LVGL_TASK_STACK_SIZE_KB 8
#define LVGL_TASK_PRIORITY 3
#define LVGL_TICK_PERIOD_MS 2

#endif // _CONFIG_H